---
# Change to suit you situation/location
timezone: Europe/Amsterdam
chrony_ntp_servers: [0.nl.pool.ntp.org, 1.nl.pool.ntp.org, 2.nl.pool.ntp.org, 3.nl.pool.ntp.org ]
chrony_config_path: /etc/chrony.conf
chrony_keyfile_path: /etc/chrony.keys
chrony_driftfile_path: /var/lib/chrony/drift
chrony_rtc: rtcsync
chrony_client_log: noclientlog
chrony_max_step: makestep 10 3
chrony_bind_addresses:
 - ::1
 - 127.0.0.1
chrony_stratum_weight: stratumweight 0
chrony_server_settings: iburst
chrony_generate_command_key: generatecommandkey
